name: Test

on:
  workflow_dispatch:        # Manual trigger only

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.2'

    - name: Install R package dependencies
      run: |
        R -e 'install.packages(c("httr", "jsonlite", "googlesheets4", "dplyr"), repos = "https://cloud.r-project.org")'

    - name: Run R script
      env:
        GCP_SHEETS_KEY: ${{ secrets.GCP_SHEETS_KEY }}
        GOOGLEMAPS_API_KEY: ${{ secrets.GOOGLEMAPS_API_KEY }}
      run: |
        Rscript code/test.R
